App\Entity\User\BaseUser:
    exclusion_policy: ALL
    properties:
        email:
            expose: true
            type: string
        lastName:
            expose: true
            type: string
        firstName:
            expose: true
            type: string
